#114: Refactored BackgroundPeerState
exasol/advanced-analytics-framework pull request #115
Opened 2023-08-03 12:46 UTC by tkilias

2023-08-04 11:03 UTC, kaklakariada requested changes

2023-08-07 07:25 UTC, tkilias commented on tests/udf_communication/peer_communication/test_add_peer_forward.py
> +REPETITIONS_FOR_FUNCTIONALITY = 3
this is local constant

2023-08-07 09:38 UTC, tkilias commented on exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
> +    )
The local variables might be in the future parameters, for that reason, I would keep it for the moment as is

2023-08-07 11:31 UTC, kaklakariada approved these changes

2023-08-07 12:29 UTC, merged